


SELECT FYEAR AS Financial_year, SUM(FAE) AS Admission_episodes
FROM hdis_10years.hes_apc_2122_hdis_10years
-- Finished episodes only (3)
WHERE EPISTAT = '3'
-- Admission episode
AND FAE = 1
-- Ordinary admission (1), day case (2) or maternity (5)
AND CLASSPAT IN ('1','2','5')
-- Emergency admissions
AND ADMIMETH LIKE ('2%')
-- First episode of a spell
AND EPIORDER = 1
-- causes and conditions 
-- external cause is a fall
AND CAUSE_3 RLIKE ('W[01]')
-- primary diagnosis is injury 
AND DIAG_3_01 RLIKE ('S|T') 
-- England and Unknown LAD only
AND RESLADST_ONS RLIKE ('E|U')
-- Aged 65+
AND STARTAGE_CALC >= 65
GROUP BY Financial_year

-- This is also too big (returns more than 1,000,000 records) - we need to split it up
SELECT FYEAR AS Financial_year, SUM(FAE) AS Admission_episodes, CASE WHEN SEX = 1 THEN 'Male' WHEN SEX = 2 THEN 'Female' ELSE 'Unknown' END AS Sex,  CASE WHEN STARTAGE_CALC BETWEEN 0 AND 4 THEN '0-4 years' WHEN STARTAGE_CALC BETWEEN 5 AND 9 THEN '5-9 years' WHEN STARTAGE_CALC BETWEEN 10 AND 14 THEN '10-14 years' WHEN STARTAGE_CALC BETWEEN 15 AND 19 THEN '15-19 years' WHEN STARTAGE_CALC BETWEEN 20 AND 24 THEN '20-24 years' WHEN STARTAGE_CALC BETWEEN 25 AND 29 THEN '25-29 years' WHEN STARTAGE_CALC BETWEEN 30 AND 34 THEN '30-34 years' WHEN STARTAGE_CALC BETWEEN 35 AND 39 THEN '35-39 years' WHEN STARTAGE_CALC BETWEEN 40 AND 44 THEN '40-44 years' WHEN STARTAGE_CALC BETWEEN 45 AND 49 THEN '45-49 years' WHEN STARTAGE_CALC BETWEEN 50 AND 54 THEN '50-54 years' WHEN STARTAGE_CALC BETWEEN 55 AND 59 THEN '55-59 years' WHEN STARTAGE_CALC BETWEEN 60 AND 64 THEN '60-64 years' WHEN STARTAGE_CALC BETWEEN 65 AND 69 THEN '65-69 years' WHEN STARTAGE_CALC BETWEEN 70 AND 74 THEN '70-74 years' WHEN STARTAGE_CALC BETWEEN 75 AND 79 THEN '75-79 years' WHEN STARTAGE_CALC BETWEEN 80 AND 84 THEN '80-84 years' WHEN STARTAGE_CALC BETWEEN 85 AND 89 THEN '85-89 years' WHEN STARTAGE_CALC BETWEEN 90 AND 120 THEN '90+ years' ELSE 'Unknown' END AS Age_group, LSOA11 AS LSOA11CD
FROM hdis_10years.hes_apc_1819_hdis_10years
-- Finished episodes only (3)
WHERE EPISTAT = '3'
-- Admission episode
AND FAE = 1
-- Ordinary admission (1), day case (2) or maternity (5)
AND CLASSPAT IN ('1','2','5')
-- Emergency admissions
AND ADMIMETH LIKE ('2%')
-- First episode of a spell
AND EPIORDER = 1
-- causes and conditions 
-- external cause is a fall
AND CAUSE_3 RLIKE ('W[01]')
-- primary diagnosis is injury 
AND DIAG_3_01 RLIKE ('S|T') 
-- England and Unknown LAD only
AND RESLADST_ONS RLIKE ('E|U')
GROUP BY LSOA11CD, Sex, Age_group, Financial_year
UNION -- this joins the results of queries together
SELECT FYEAR AS Financial_year, SUM(FAE) AS Admission_episodes, CASE WHEN SEX = 1 THEN 'Male' WHEN SEX = 2 THEN 'Female' ELSE 'Unknown' END AS Sex,  CASE WHEN STARTAGE_CALC BETWEEN 0 AND 4 THEN '0-4 years' WHEN STARTAGE_CALC BETWEEN 5 AND 9 THEN '5-9 years' WHEN STARTAGE_CALC BETWEEN 10 AND 14 THEN '10-14 years' WHEN STARTAGE_CALC BETWEEN 15 AND 19 THEN '15-19 years' WHEN STARTAGE_CALC BETWEEN 20 AND 24 THEN '20-24 years' WHEN STARTAGE_CALC BETWEEN 25 AND 29 THEN '25-29 years' WHEN STARTAGE_CALC BETWEEN 30 AND 34 THEN '30-34 years' WHEN STARTAGE_CALC BETWEEN 35 AND 39 THEN '35-39 years' WHEN STARTAGE_CALC BETWEEN 40 AND 44 THEN '40-44 years' WHEN STARTAGE_CALC BETWEEN 45 AND 49 THEN '45-49 years' WHEN STARTAGE_CALC BETWEEN 50 AND 54 THEN '50-54 years' WHEN STARTAGE_CALC BETWEEN 55 AND 59 THEN '55-59 years' WHEN STARTAGE_CALC BETWEEN 60 AND 64 THEN '60-64 years' WHEN STARTAGE_CALC BETWEEN 65 AND 69 THEN '65-69 years' WHEN STARTAGE_CALC BETWEEN 70 AND 74 THEN '70-74 years' WHEN STARTAGE_CALC BETWEEN 75 AND 79 THEN '75-79 years' WHEN STARTAGE_CALC BETWEEN 80 AND 84 THEN '80-84 years' WHEN STARTAGE_CALC BETWEEN 85 AND 89 THEN '85-89 years' WHEN STARTAGE_CALC BETWEEN 90 AND 120 THEN '90+ years' ELSE 'Unknown' END AS Age_group, LSOA11 AS LSOA11CD
FROM hdis_10years.hes_apc_1920_hdis_10years
-- Finished episodes only (3)
WHERE EPISTAT = '3'
-- Admission episode
AND FAE = 1
-- Ordinary admission (1), day case (2) or maternity (5)
AND CLASSPAT IN ('1','2','5')
-- Emergency admissions
AND ADMIMETH LIKE ('2%')
-- First episode of a spell
AND EPIORDER = 1
-- causes and conditions 
-- external cause is a fall
AND CAUSE_3 RLIKE ('W[01]')
-- primary diagnosis is injury 
AND DIAG_3_01 RLIKE ('S|T') 
-- England and Unknown LAD only
AND RESLADST_ONS RLIKE ('E|U')
GROUP BY LSOA11CD, Sex, Age_group, Financial_year

SELECT FYEAR AS Financial_year, SUM(FAE) AS Admission_episodes, CASE WHEN SEX = 1 THEN 'Male' WHEN SEX = 2 THEN 'Female' ELSE 'Unknown' END AS Sex,  CASE WHEN STARTAGE_CALC BETWEEN 0 AND 4 THEN '0-4 years' WHEN STARTAGE_CALC BETWEEN 5 AND 9 THEN '5-9 years' WHEN STARTAGE_CALC BETWEEN 10 AND 14 THEN '10-14 years' WHEN STARTAGE_CALC BETWEEN 15 AND 19 THEN '15-19 years' WHEN STARTAGE_CALC BETWEEN 20 AND 24 THEN '20-24 years' WHEN STARTAGE_CALC BETWEEN 25 AND 29 THEN '25-29 years' WHEN STARTAGE_CALC BETWEEN 30 AND 34 THEN '30-34 years' WHEN STARTAGE_CALC BETWEEN 35 AND 39 THEN '35-39 years' WHEN STARTAGE_CALC BETWEEN 40 AND 44 THEN '40-44 years' WHEN STARTAGE_CALC BETWEEN 45 AND 49 THEN '45-49 years' WHEN STARTAGE_CALC BETWEEN 50 AND 54 THEN '50-54 years' WHEN STARTAGE_CALC BETWEEN 55 AND 59 THEN '55-59 years' WHEN STARTAGE_CALC BETWEEN 60 AND 64 THEN '60-64 years' WHEN STARTAGE_CALC BETWEEN 65 AND 69 THEN '65-69 years' WHEN STARTAGE_CALC BETWEEN 70 AND 74 THEN '70-74 years' WHEN STARTAGE_CALC BETWEEN 75 AND 79 THEN '75-79 years' WHEN STARTAGE_CALC BETWEEN 80 AND 84 THEN '80-84 years' WHEN STARTAGE_CALC BETWEEN 85 AND 89 THEN '85-89 years' WHEN STARTAGE_CALC BETWEEN 90 AND 120 THEN '90+ years' ELSE 'Unknown' END AS Age_group, LSOA11 AS LSOA11CD
FROM hdis_10years.hes_apc_2021_hdis_10years
-- Finished episodes only (3)
WHERE EPISTAT = '3'
-- Admission episode
AND FAE = 1
-- Ordinary admission (1), day case (2) or maternity (5)
AND CLASSPAT IN ('1','2','5')
-- Emergency admissions
AND ADMIMETH LIKE ('2%')
-- First episode of a spell
AND EPIORDER = 1
-- causes and conditions 
-- external cause is a fall
AND CAUSE_3 RLIKE ('W[01]')
-- primary diagnosis is injury 
AND DIAG_3_01 RLIKE ('S|T') 
-- England and Unknown LAD only
AND RESLADST_ONS RLIKE ('E|U')
GROUP BY LSOA11CD, Sex, Age_group, Financial_year
UNION -- this joins the results of queries together
SELECT FYEAR AS Financial_year, SUM(FAE) AS Admission_episodes, CASE WHEN SEX = 1 THEN 'Male' WHEN SEX = 2 THEN 'Female' ELSE 'Unknown' END AS Sex,  CASE WHEN STARTAGE_CALC BETWEEN 0 AND 4 THEN '0-4 years' WHEN STARTAGE_CALC BETWEEN 5 AND 9 THEN '5-9 years' WHEN STARTAGE_CALC BETWEEN 10 AND 14 THEN '10-14 years' WHEN STARTAGE_CALC BETWEEN 15 AND 19 THEN '15-19 years' WHEN STARTAGE_CALC BETWEEN 20 AND 24 THEN '20-24 years' WHEN STARTAGE_CALC BETWEEN 25 AND 29 THEN '25-29 years' WHEN STARTAGE_CALC BETWEEN 30 AND 34 THEN '30-34 years' WHEN STARTAGE_CALC BETWEEN 35 AND 39 THEN '35-39 years' WHEN STARTAGE_CALC BETWEEN 40 AND 44 THEN '40-44 years' WHEN STARTAGE_CALC BETWEEN 45 AND 49 THEN '45-49 years' WHEN STARTAGE_CALC BETWEEN 50 AND 54 THEN '50-54 years' WHEN STARTAGE_CALC BETWEEN 55 AND 59 THEN '55-59 years' WHEN STARTAGE_CALC BETWEEN 60 AND 64 THEN '60-64 years' WHEN STARTAGE_CALC BETWEEN 65 AND 69 THEN '65-69 years' WHEN STARTAGE_CALC BETWEEN 70 AND 74 THEN '70-74 years' WHEN STARTAGE_CALC BETWEEN 75 AND 79 THEN '75-79 years' WHEN STARTAGE_CALC BETWEEN 80 AND 84 THEN '80-84 years' WHEN STARTAGE_CALC BETWEEN 85 AND 89 THEN '85-89 years' WHEN STARTAGE_CALC BETWEEN 90 AND 120 THEN '90+ years' ELSE 'Unknown' END AS Age_group, LSOA11 AS LSOA11CD
FROM hdis_10years.hes_apc_2122_hdis_10years
-- Finished episodes only (3)
WHERE EPISTAT = '3'
-- Admission episode
AND FAE = 1
-- Ordinary admission (1), day case (2) or maternity (5)
AND CLASSPAT IN ('1','2','5')
-- Emergency admissions
AND ADMIMETH LIKE ('2%')
-- First episode of a spell
AND EPIORDER = 1
-- causes and conditions 
-- external cause is a fall
AND CAUSE_3 RLIKE ('W[01]')
-- primary diagnosis is injury 
AND DIAG_3_01 RLIKE ('S|T') 
-- England and Unknown LAD only
AND RESLADST_ONS RLIKE ('E|U')
GROUP BY LSOA11CD, Sex, Age_group, Financial_year

SELECT FYEAR AS Financial_year, SUM(FAE) AS Admission_episodes, CASE WHEN SEX = 1 THEN 'Male' WHEN SEX = 2 THEN 'Female' ELSE 'Unknown' END AS Sex,  CASE WHEN STARTAGE_CALC BETWEEN 0 AND 4 THEN '0-4 years' WHEN STARTAGE_CALC BETWEEN 5 AND 9 THEN '5-9 years' WHEN STARTAGE_CALC BETWEEN 10 AND 14 THEN '10-14 years' WHEN STARTAGE_CALC BETWEEN 15 AND 19 THEN '15-19 years' WHEN STARTAGE_CALC BETWEEN 20 AND 24 THEN '20-24 years' WHEN STARTAGE_CALC BETWEEN 25 AND 29 THEN '25-29 years' WHEN STARTAGE_CALC BETWEEN 30 AND 34 THEN '30-34 years' WHEN STARTAGE_CALC BETWEEN 35 AND 39 THEN '35-39 years' WHEN STARTAGE_CALC BETWEEN 40 AND 44 THEN '40-44 years' WHEN STARTAGE_CALC BETWEEN 45 AND 49 THEN '45-49 years' WHEN STARTAGE_CALC BETWEEN 50 AND 54 THEN '50-54 years' WHEN STARTAGE_CALC BETWEEN 55 AND 59 THEN '55-59 years' WHEN STARTAGE_CALC BETWEEN 60 AND 64 THEN '60-64 years' WHEN STARTAGE_CALC BETWEEN 65 AND 69 THEN '65-69 years' WHEN STARTAGE_CALC BETWEEN 70 AND 74 THEN '70-74 years' WHEN STARTAGE_CALC BETWEEN 75 AND 79 THEN '75-79 years' WHEN STARTAGE_CALC BETWEEN 80 AND 84 THEN '80-84 years' WHEN STARTAGE_CALC BETWEEN 85 AND 89 THEN '85-89 years' WHEN STARTAGE_CALC BETWEEN 90 AND 120 THEN '90+ years' ELSE 'Unknown' END AS Age_group, LSOA11 AS LSOA11CD
FROM hdis_10years.hes_apc_2223_hdis_10years
-- Finished episodes only (3)
WHERE EPISTAT = '3'
-- Admission episode
AND FAE = 1
-- Ordinary admission (1), day case (2) or maternity (5)
AND CLASSPAT IN ('1','2','5')
-- Emergency admissions
AND ADMIMETH LIKE ('2%')
-- First episode of a spell
AND EPIORDER = 1
-- causes and conditions 
-- external cause is a fall
AND CAUSE_3 RLIKE ('W[01]')
-- primary diagnosis is injury 
AND DIAG_3_01 RLIKE ('S|T') 
-- England and Unknown LAD only
AND RESLADST_ONS RLIKE ('E|U')
GROUP BY LSOA11CD, Sex, Age_group, Financial_year